---
- name: Install Git on remote hosts
  hosts: all
  become: true
  tasks:
    - name: Update package cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure git is installed (cross-platform)
      package:
        name: git
        state: present
