---
- hosts: all
  become: true
  gather_facts: yes

  vars:
    root_dir: /usr/share/nginx/html
    server_message: "This is server {{ ansible_hostname }}!"

  tasks:
    - name: Install nginx and cowsay
      apt:
        name:
          - nginx
          - cowsay
        state: present
        update_cache: yes

    - name: Run cowsay with server name
      command: cowsay "{{ server_message }}"
      register: cowsay_result

    - name: Render index.html template
      template:
        src: templates/index.html.j2
        dest: "{{ root_dir }}/index.html"
        owner: www-data
        group: www-data
        mode: "0644"
      notify: restart nginx

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
